
modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
logoFile="lodestone.png"
modId="lodestone"
version="${file.jarVersion}"
displayName="Lodestone"
authors="The Lodestar Team;"
description='''
A library containing various utilities.
'''
[[dependencies.lodestone]]
modId = "forge"
mandatory = true
versionRange = "[40.2,)"
ordering = "NONE"
side = "BOTH"