#version 430 core

layout (local_size_x = 10, local_size_y = 10, local_size_z = 10) in;


layout(rgba16f, binding = 0) uniform image3D imgOutput;

layout(std430, binding = 1) buffer Vertices {
	vec3 vertices[];
};

//layout(std430, binding = 2) buffer Indices {
//	uint indices[];
//};

float sdfSphere(vec3 p, vec3 center, float radius) {
	return length(p - center) - radius;
}

void main() {
	ivec3 pixelCoords = ivec3(gl_GlobalInvocationID);
	vec3 uv = vec3(pixelCoords) / vec3(imageSize(imgOutput));

	vec3 center = vec3(0.5);
	float radius = 0.25;
	float distance = sdfSphere(uv, center, radius);
	imageStore(imgOutput, pixelCoords, vec4(vec3(distance), 1.0));

	//imageStore(imgOutput, pixelCoords, vec4(vertices[2], 1.0));
}